### ISSUE TITLE
Convert Epub to Pdf

### ISSUE THREAD

**Issue by GeorgeS2019** [vers-one/EpubReader#39]
Do you have a plan to provide this feature?

**Comment by vers-one** [comment]
Unfortunately, an implementation of such feature would probably require 50-100 times more code than this library currently has and it would also require some setup for the conversion. PDF is a fixed-layout paged-based format (i.e. it determines how the whole page should look like) while EPUB is a flow-layout format which doesn't have page breaks and can be easily scaled to occupy the whole screen of the device regardless of its size and aspect ratio. In order to convert EPUB to PDF user would have to set up page size, styles, fonts, font sizes, margins, table of contents' rendering options and so on.

Additionally, it might also require to introduce a dependency on some HTML rendering engine which will make this library platform-dependent.
