### ISSUE TITLE
Load images and CSS files from EPUB archive even if they are missing in EPUB manifest

### ISSUE THREAD

**Issue by git-Charlie** [vers-one/EpubReader#44]
## Description

1.  The file "**fb.opf**" cannot be found in  `EpubBook.Content.AllFiles`;
2. When I edit the **fb.opt** file, I add the item manifest to it.  `EpubBook.Content.AllFiles` will changed accordingly;
3. Sorry I didn't read the epub spec in detail, the WPF demo can't display any images from the last chapter because it is not included in the opt file  manifest .I don't think a strict reliance on manifest is appropriate.

## Sample EPUB file

[test-file.epub.zip](https://github.com/vers-one/EpubReader/files/8360245/test-file.epub.zip)

Some pictures in the last chapter of the file

**Comment by vers-one** [comment]
1 and 2. Could you please clarify, are you expecting to see the **fb.opf** file in `EpubBook.Content.AllFiles` and cannot find it there? If so, then this is the correct behavior because **fb.opf** is the **schema** file while `EpubBook.Content.AllFiles` contains the list of all the **content** files.
3. Yes, you are correct. Those images don't get displayed because they are not included in the manifest which is required by the EPUB standard. I know that some EPUB readers relax this restriction by searching the file directly in the EPUB archive if it is missing in the manifest. Starting from EpubReader v3.1.1 you can get the physical file path of a content file via its `FilePathInEpubArchive` property. I also updated WPF demo app to load images and CSS files directly from the EPUB archive if they are missing in the manifest. Could you try it out and see if it works for you?

**Comment by vers-one** [comment]
Implemented in v3.1.1.

Please reopen this issue if you still have concerns about the first two questions.
