### ISSUE TITLE
Internal.ContentReader.ParseContentMap(EpubBookRef bookRef, ContentReaderOptions contentReaderOptions)

### ISSUE THREAD

**Issue by Marion64** [vers-one/EpubReader#74]
## Description
I have used the Daisy Pipeline2 to convert daisy2.02 and daisy3 books to epub. When using the library to read the converted books the library crashes (Even with all ignore and suppress options activated) and reports the following exceptions - 

System.AggregateException: 'One or more errors occurred. (Object reference not set to an instance of an object.)'

Inner Exception
NullReferenceException: Object reference not set to an instance of an object.

## Sample EPUB file

[Absolute_Risk_Epub.zip](https://github.com/vers-one/EpubReader/files/10308277/Absolute_Risk_Epub.zip)

## Additional context
The exceptions that my software reports don't really provide much information. To get more information about what's happening and what's causing the library to crash, you would have to run the epub file in the source code. I couldn't run the source code project myself, because I can't find the framework 4.6 installer for my computer.

**Comment by vers-one** [comment]
Hmm, that's interesting. Custom exceptions have been added [a few months ago](https://github.com/vers-one/EpubReader/commit/451e33990ecebbbc932abe33c7d2213a8843180b), so this error should have been reported as `EpubContentException` with the following message: `EPUB parsing error: file "EPUB/images/cover.jpg" was not found in the EPUB file` (the cause of the error is the lack of the images declared in the EPUB manifest in the *EPUB\package.opf* file). Could you let me know which version of the library you are using?

If you want to suppress those types of errors, you can use the `ContentReaderOptions.ContentFileMissing` event ([example](https://github.com/vers-one/EpubReader/blob/52666a9efa87b05fd5023093df4a269d5951995c/Source/VersOne.Epub.WpfDemo/Models/BookModel.cs#L21-L25), [documentation](https://os.vers.one/EpubReader/malformed-epub/index.html#missing-content-files)). This event is available since version 3.2.

You don't have to install .NET Framework 4.6 to build the code, you only need .NET Framework 4.6 Targeting Pack which can be added individually through Visual Studio 2022 installer. Alternatively, you can change the target framework to .NET Framework 4.8 in the project settings or unload WpfDemo project (which is the only one that requires .NET Framework) and use .NET Core or .NET 5-7 to build the rest of the code.

**Comment by Marion64** [comment]
I was running the source DLL build in framework 4.6.2 and it seems like it wasn't working well with that. What fixed the issue for me was running the DLL build in framework 4.8 and referencing it in my framework 4.8 project. 

Thank you for proposing the change in the framework solution.
