### ISSUE TITLE
EPUBs with wrong cover tag are not read

### ISSUE THREAD

**Issue by IvoMajic** [vers-one/EpubReader#79]
## Description
Seems that there is something wrong when reading the cover tag of this particular EPUB (can not share it as it is copyrighted, but the publisher is Packt Publishing). Seems to me that in this case, the library should just log a warning and simply not read/use the cover image eg. treating it as if it has no cover (similar to https://github.com/vers-one/EpubReader/issues/75).

I still have not found the root cause of this particular EPUB (the cover file Images/default_cover.jpeg does exist), but it seems like a non-critical error that should not cause the whole book from loading.

```
There was an exception when opening epub book: /books/MyBook.epub
VersOne.Epub.EpubPackageException: Incorrect EPUB manifest: item with ID = "Images/default_cover.jpeg" is missing.
   at VersOne.Epub.Utils.TaskExtensionMethods.ExecuteAndUnwrapAggregateException[T](Task`1 task)
```

**Comment by vers-one** [comment]
This is actually different from #75. It is hard to determine the cause of the error without looking into the book's OPF file but I suspect that there is a `<meta name="cover" ... />` element pointing to `"Images/default_cover.jpeg"`. This value is actually not a path to the file but rather an ID of a manifest item which means there must be an `<item id="Images/default_cover.jpeg" ...>` in the `<manifest>` section in the same OPF file. I assume there is no such manifest item which is why EpubReader says that this is an incorrect EPUB manifest.

**Comment by IvoMajic** [comment]
You are correct, I thought it was a cover issue in general (this is why I referenced the "no cover" issue) - but after looking at the metadata closely it turned out to be exactly as you suspected - the item was missing.
