### ISSUE TITLE
Epub3 Creator roles aren't populating

### ISSUE THREAD

**Issue by majora2007** [vers-one/EpubReader#80]
## Description
Creators roles are missing. In the example we have to creators, but when it's inspected, EpubReader has `null` Role value, whereas it should be "aut" and "ill".

```
<dc:creator id="creator01">Ameko Kaeruda</dc:creator>
    <meta property="alternate-script" refines="#creator01" xml:lang="ja">蛙田 アメコ</meta>
    <meta property="file-as" refines="#creator01">Kaeruda, Ameko</meta>
    <meta property="role" refines="#creator01" scheme="marc:relators">aut</meta>
    <dc:creator id="creator02">Sencha</dc:creator>
    <meta property="alternate-script" refines="#creator02" xml:lang="ja">せんちゃ</meta>
    <meta property="file-as" refines="#creator02">Sencha</meta>
    <meta property="role" refines="#creator02" scheme="marc:relators">ill</meta>
    ```

## EPUB specification link
https://www.w3.org/publishing/epub3/epub-packages.html#sec-role

**Comment by vers-one** [comment]
EpubReader doesn't perform any post-processing when it parses a `<dc:creator>` XML element into an instance of the `EpubMetadataCreator` class. `FileAs` and `Role` properties will be populated only if they are part of the same element, e.g.:
https://github.com/vers-one/EpubReader/blob/52666a9efa87b05fd5023093df4a269d5951995c/Source/VersOne.Epub.Test/Unit/Readers/PackageReaderTests.cs#L63

The data from the `<meta>` XML elements are available through the `EpubBook.Schema.Package.Metadata.MetaItems` array.

**Comment by majora2007** [comment]
Ahh okay, interesting. I've only ever see it separated, but having access via `EpubBook.Schema.Package.Metadata.MetaItems` is more than acceptable. 

Thanks for the quick response. Btw, looking forward to Media Overlays PR :)

**Comment by vers-one** [comment]
When I first implemented this in 2018, most EPUB 3 books were still using EPUB 2 way of defining contributors and creators — with inline roles and file-as values: https://idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.2.2 (it is allowed in EPUB 3 too, for backwards compatibility). But now, more and more books switch to EPUB 3 metadata (with `<meta refines="..." />` elements), especially when they need to include the names in more than one language.

I might add some post-processing for those elements to re-expose the combined data (`<dc:creator>` / `<dc:contributor>` + `<meta refines="..." />`) on the `EpubBook` level after I finish with the 3.3 release. Unfortunately, it won't cover 100% use cases allowed by the EPUB 3 specification because the spec lets `<meta>` elements to have arbitrary properties (e.g. `<meta property="my-property" refines="#creator01" scheme="my:scheme">some value</meta>`) but at least it will be able cover most common use cases.

**Comment by majora2007** [comment]
I think that would be great honestly because I'm also looking at something like:

```
    <dc:title id="t3">The New French Cuisine Masters</dc:title>
    <meta refines="#t3" property="title-type">collection</meta>
    <meta refines="#t3" property="display-seq">3</meta>
```
https://www.w3.org/publishing/epub3/epub-packages.html#sec-title-type

and trying to generate an ordered reading list. But it's extra complicated because I have to walk through all metadata items and when we catch the collection, then loop through items twice to get information.  Streamlining so the consumer doesn't need to look so much into internals would be great (but still have the option if they want).
